#!/bin/bash

# Word pretrained ASIMOV
python3 model_rnn_sfgram.py --author0 ASIMOV --hidden-size 25  --cell-size 25 --embedding-size 60 --feature c3 --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output-dropout 0.5 --output outputs/sfgram/ --name "SFG ASIMOV GRU 25-25 C3-T" --description "Authorship Verification ASIMOV SFGram GRU 25 hidden neurons, Character trigram (C3) trained" --rnn-type GRU --epoch 50 --batch-size 256 --verbose 4 --cuda
# python3 model_rnn_sfgram.py --author0 ASIMOV --hidden-size 50  --cell-size 50 --embedding-size 60 --feature c3 --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output-dropout 0.5 --output outputs/sfgram/ --name "SFG ASIMOV GRU 50-50 C3-T" --description "Authorship Verification ASIMOV SFGram GRU 50 hidden neurons, Character trigram (C3) trained" --rnn-type GRU --epoch 55 --batch-size 256 --verbose 4 --cuda
# python3 model_rnn_sfgram.py --author0 ASIMOV --hidden-size 100 --cell-size 100 --embedding-size 60 --feature c3 --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output-dropout 0.5 --output outputs/sfgram/ --name "SFG ASIMOV GRU 100-100 C3-T" --description "Authorship Verification ASIMOV SFGram GRU 100 hidden neurons, Character trigram (C3) trained" --rnn-type GRU --epoch 60 --batch-size 256 --verbose 4 --cuda

# Word pretrained DICK
# python3 model_rnn_sfgram.py --author0 DICK --hidden-size 25  --cell-size 25 --embedding-size 60 --feature c3 --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output-dropout 0.5 --output outputs/sfgram/ --name "SFG DICK GRU 25-25 C3-T" --description "Authorship Verification DICK SFGram GRU 25 hidden neurons, Character trigram (C3) trained" --rnn-type GRU --epoch 50 --batch-size 256 --verbose 4 --cuda
# python3 model_rnn_sfgram.py --author0 DICK --hidden-size 50  --cell-size 50 --embedding-size 60 --feature c3 --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output-dropout 0.5 --output outputs/sfgram/ --name "SFG DICK GRU 50-50 C3-T" --description "Authorship Verification DICK SFGram GRU 50 hidden neurons, Character trigram (C3) trained" --rnn-type GRU --epoch 55 --batch-size 256 --verbose 4 --cuda
# python3 model_rnn_sfgram.py --author0 DICK --hidden-size 100 --cell-size 100 --embedding-size 60 --feature c3 --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output-dropout 0.5 --output outputs/sfgram/ --name "SFG DICK GRU 100-100 C3-T" --description "Authorship Verification DICK SFGram GRU 100 hidden neurons, Character trigram (C3) trained" --rnn-type GRU --epoch 60 --batch-size 256 --verbose 4 --cuda

# Word pretrained SILVERBERG
# python3 model_rnn_sfgram.py --author0 SILVERBERG --hidden-size 25  --cell-size 25 --embedding-size 60 --feature c3 --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output-dropout 0.5 --output outputs/sfgram/ --name "SFG SILVERBERG GRU 25-25 C3-T" --description "Authorship Verification SILVERBERG SFGram GRU 25 hidden neurons, Character trigram (C3) trained" --rnn-type GRU --epoch 50 --batch-size 256  --verbose 4 --cuda
# python3 model_rnn_sfgram.py --author0 SILVERBERG --hidden-size 50  --cell-size 50 --embedding-size 60 --feature c3 --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output-dropout 0.5 --output outputs/sfgram/ --name "SFG SILVERBERG GRU 50-50 C3-T" --description "Authorship Verification SILVERBERG SFGram GRU 50 hidden neurons, Character trigram (C3) trained" --rnn-type GRU --epoch 55 --batch-size 256 --verbose 4 --cuda
# python3 model_rnn_sfgram.py --author0 SILVERBERG --hidden-size 100 --cell-size 100 --embedding-size 60 --feature c3 --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output-dropout 0.5 --output outputs/sfgram/ --name "SFG SILVERBERG GRU 100-100 C3-T" --description "Authorship Verification SILVERBERG SFGram GRU 100 hidden neurons, Character trigram (C3) trained" --rnn-type GRU --epoch 60 --batch-size 256 --verbose 4 --cuda
