#!/bin/bash

# python model_rnn_keras.py --hidden-size 100 --cell-size 100 --embedding-size 30 --feature c2 --learning-window 40 --max-length 40 --k 10 --output outputs/ --name "AA Na15 LSTM 100-100 C2-P keras" --description "Authorship Attribution 15 authors LSTM 100 hidden neurons, Character (C2) pretrained" --rnn-type LSTM --epoch 350 --batch-size 32 --pretrained --verbose 4 --cuda --embedding-path ~/Projets/TURING/Recherches/MLE/PhD/Reuters-C50-Authorship-Attribution/embeddings/char_embedding/c2_cx2_d30.p --cuda

# python model_rnn_keras.py --hidden-size 200 --cell-size 200 --embedding-size 30 --feature c2 --learning-window 40 --max-length 40 --k 10 --output outputs/ --name "AA Na15 LSTM 200-200 C2-P keras" --description "Authorship Attribution 15 authors LSTM 200 hidden neurons, Character (C2) pretrained" --rnn-type LSTM --epoch 350 --batch-size 32 --pretrained --verbose 4 --cuda --embedding-path ~/Projets/TURING/Recherches/MLE/PhD/Reuters-C50-Authorship-Attribution/embeddings/char_embedding/c2_cx2_d30.p --cuda

python2.7 model_rnn_keras.py --hidden-size 300 --cell-size 300 --embedding-size 30 --feature c2 --learning-window 40 --max-length 40 --k 10 --output outputs/ --name "AA Na15 LSTM 300-300 C2-P keras 2" --description "Authorship Attribution 15 authors LSTM 300 hidden neurons, Character (C2) pretrained" --rnn-type LSTM --epoch 350 --batch-size 32 --pretrained --verbose 4 --cuda --embedding-path ~/Projets/TURING/Recherches/MLE/PhD/Reuters-C50-Authorship-Attribution/embeddings/char_embedding/c2_cx2_d30.p --cuda

# python2.7 model_rnn_keras.py --hidden-size 100 --cell-size 100 --embedding-size 30 --feature c2 --learning-window 40 --max-length 40 --k 10 --output outputs/ --name "AA Na15 LSTM 100-100 C2-10 keras" --description "Authorship Attribution 15 authors LSTM 100 hidden neurons, Character (C2)" --rnn-type LSTM --epoch 350 --batch-size 32 --verbose 4 --cuda --embedding-path ~/Projets/TURING/Recherches/MLE/PhD/Reuters-C50-Authorship-Attribution/embeddings/char_embedding/c2_cx2_d30.p --cuda

# python2.7 model_rnn_keras.py --hidden-size 200 --cell-size 200 --embedding-size 30 --feature c2 --learning-window 40 --max-length 40 --k 10 --output outputs/ --name "AA Na15 LSTM 200-200 C2-10 keras" --description "Authorship Attribution 15 authors LSTM 200 hidden neurons, Character (C2)" --rnn-type LSTM --epoch 350 --batch-size 32 --verbose 4 --cuda --embedding-path ~/Projets/TURING/Recherches/MLE/PhD/Reuters-C50-Authorship-Attribution/embeddings/char_embedding/c2_cx2_d30.p --cuda

# python2.7 model_rnn_keras.py --hidden-size 300 --cell-size 300 --embedding-size 30 --feature c2 --learning-window 40 --max-length 40 --k 10 --output outputs/ --name "AA Na15 LSTM 300-300 C2-10 keras" --description "Authorship Attribution 15 authors LSTM 300 hidden neurons, Character (C2)" --rnn-type LSTM --epoch 350 --batch-size 32 --verbose 4 --cuda --embedding-path ~/Projets/TURING/Recherches/MLE/PhD/Reuters-C50-Authorship-Attribution/embeddings/char_embedding/c2_cx2_d30.p --cuda
