#!/usr/bin/env bash

python3 model_rnn_sfgram.py --author0 ASIMOV --hidden-size 100  --cell-size 100 --embedding-size 300 --feature wv --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output outputs/sfgram/ --xpname "SFG ASIMOV GRU 100-100 WV-P COUNT" --description "Authorship Verification ASIMOV SFGram GRU 25 hidden neurons, Word Vectors (WV) pre-trained" --rnn-type GRU --epoch 1 --pretrained --batch-size 4 --verbose 4

python3 model_rnn_sfgram.py --author0 ASIMOV --hidden-size 25  --cell-size 25 --embedding-size 100 --feature wv --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output outputs/sfgram/ --xpname "SFG ASIMOV GRU 25-25 WV-T COUNT" --description "Authorship Verification ASIMOV SFGram GRU 25 hidden neurons, Word Vectors (WV) trained" --rnn-type GRU --epoch 1 --batch-size 4 --verbose 4

python3 model_rnn_sfgram.py --author0 ASIMOV --hidden-size 50  --cell-size 50 --embedding-size 10 --feature c1 --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output-dropout 0.5 --output outputs/sfgram/ --xpname "SFG ASIMOV GRU 50-50 C1-P COUNT" --description "Authorship Verification ASIMOV SFGram GRU 50 hidden neurons, Character unigram (C1) pre-trained" --rnn-type GRU --epoch 1 --pretrained --batch-size 4 --embedding-path ~/Projets/TURING/Recherches/PhD/LSTM-GRU-authorship-attribution/embeddings/char_embedding/c1_cx2_d10.p --verbose 4

python3 model_rnn_sfgram.py --author0 ASIMOV --hidden-size 100 --cell-size 100 --embedding-size 10 --feature c1 --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output-dropout 0.5 --output outputs/sfgram/ --xpname "SFG ASIMOV GRU 100-100 C1-T COUNT" --description "Authorship Verification ASIMOV SFGram GRU 100 hidden neurons, Character unigram (C1) trained" --rnn-type GRU --epoch 1 --batch-size 4 --verbose 4

python3 model_rnn_sfgram.py --author0 ASIMOV --hidden-size 50  --cell-size 50 --embedding-size 30 --feature c2 --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output-dropout 0.5 --output outputs/sfgram/ --xpname "SFG ASIMOV GRU 50-50 C2-P COUNT" --description "Authorship Verification ASIMOV SFGram GRU 50 hidden neurons, Character bigram (C2) pre-trained" --rnn-type GRU --epoch 1 --pretrained --batch-size 4 --embedding-path ~/Projets/TURING/Recherches/PhD/LSTM-GRU-authorship-attribution/embeddings/char_embedding/c2_cx2_d30.p --verbose 4

python3 model_rnn_sfgram.py --author0 ASIMOV --hidden-size 25  --cell-size 25 --embedding-size 30 --feature c2 --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output-dropout 0.5 --output outputs/sfgram/ --xpname "SFG ASIMOV GRU 25-25 C2-T COUNT" --description "Authorship Verification ASIMOV SFGram GRU 25 hidden neurons, Character bigram (C2) trained" --rnn-type GRU --epoch 1 --batch-size 4 --verbose 4

python3 model_rnn_sfgram.py --author0 ASIMOV --hidden-size 25  --cell-size 25 --embedding-size 60 --feature c3 --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output-dropout 0.5 --output outputs/sfgram/ --xpname "SFG ASIMOV GRU 25-25 C3-P COUNT" --description "Authorship Verification ASIMOV SFGram GRU 25 hidden neurons, Character trigram (C3) pre-trained" --rnn-type GRU --epoch 1 --pretrained --batch-size 4 --embedding-path ~/Projets/TURING/Recherches/PhD/LSTM-GRU-authorship-attribution/embeddings/char_embedding/c3_cx2_d60.p --verbose 4

python3 model_rnn_sfgram.py --author0 ASIMOV --hidden-size 25  --cell-size 25 --embedding-size 60 --feature c3 --learning-window 40 --max-length 40 --k 5 --zero-weight 1 --output-dropout 0.5 --output outputs/sfgram/ --xpname "SFG ASIMOV GRU 25-25 C3-T COUNT" --description "Authorship Verification ASIMOV SFGram GRU 25 hidden neurons, Character trigram (C3) trained" --rnn-type GRU --epoch 1 --batch-size 4 --verbose 4
